services:
  - type: web
    name: task-tracker
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: -Xms256m -Xmx450m
